Explicitly use FLAG_IMMUTABLE for PendingIntent
- to address:
01-04 12:11:22.075 24114 24114 E AndroidRuntime: Caused by:
java.lang.IllegalArgumentException: com.quuppa.quuppatag: Targeting S+
(version 31 and above) requires that one of FLAG_IMMUTABLE or
FLAG_MUTABLE be specified when creating a PendingIntent.
01-04 12:11:22.075 24114 24114 E AndroidRuntime: Strongly consider using
FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on
the PendingIntent being mutable, e.g. if it needs to be used with inline
replies or bubbles.